# For triggering a rebuild when docs are updated in an external repo
# Copy this file to .github/workflows/ in your documentation repository

name: Trigger website rebuild

on:
  push:
    branches: [ main ]
  
jobs:
  trigger-rebuild:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger website rebuild
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.DEPLOY_TOKEN }}
        script: |
          const response = await github.rest.repos.createDispatchEvent({
            owner: 'unternet-co',
            repo: 'unternet.co',
            event_type: 'docs-updated',
            client_payload: {
              repository: context.repo.repo,
              ref: context.ref,
              sha: context.sha
            }
          });
          
          console.log('Website rebuild triggered successfully');
          console.log('Response:', response.status);
