# Documentation Sync Trigger for External Repositories
# 
# This workflow triggers the main website's documentation sync when docs are updated.
# It uses repository dispatch events for provider-agnostic deployment - the main site
# will sync docs and trigger its own deployment via deploy hooks.
#
# Copy this file to .github/workflows/docsync.yml in your external repository.

name: Trigger documentation sync

on:
  # Trigger on all pushes to main (since docs could be anywhere)
  push:
    branches: [ main ]
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  trigger-docsync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger documentation sync
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.DOCSYNC_TOKEN }}
        script: |
          const response = await github.rest.repos.createDispatchEvent({
            owner: 'unternet-co',
            repo: 'unternet.co',
            event_type: 'docs-updated',
            client_payload: {
              repository: context.repo.repo,
              ref: context.ref,
              sha: context.sha
            }
          });
          
          console.log('Documentation sync triggered successfully');
          console.log('Response:', response.status);
